### ISSUE TITLE
class number in SYNTHIA Dataset

### ISSUE THREAD

**Issue by dongzhuoyao** [swamiviv/LSD-seg#3]
In the paper:    about SYNTHIA dataset, you use 16 common classes with cityscapes,

why these places indicate that class number is 19?

[https://github.com/swamiviv/LSD-seg/blob/master/code/train.py#L62
](https://github.com/swamiviv/LSD-seg/blob/master/code/train.py#L62
)

[https://github.com/swamiviv/LSD-seg/blob/master/code/torchfcn/datasets/segmentation_datasets.py#L261](https://github.com/swamiviv/LSD-seg/blob/master/code/torchfcn/datasets/segmentation_datasets.py#L261)

**Comment by dongzhuoyao** [comment]
got it, thank you

**Comment by chrisliu54** [comment]
Hi, I found that the labels of SYNTHIA(downloaded from official site), namely, files under `GT/LABELS`, are of 3 channels, whose max value is 3.
Could you show me how to convert this to a normal case?
@dongzhuoyao @swamiviv

**Comment by dongzhuoyao** [comment]
cv2.imread(your-image-path,cv2.IMREAD_UNCHANGED)

**Comment by FlyingQianMM** [comment]
@chrisliu54 How do you load the right labels of SYNTHIA later? I met the same situation where files under GT/LABELS are 1 channel, whose max value is 3. And I used the command cv2.imread(your-image-path,cv2.IMREAD_UNCHANGED) by @dongzhuoyao ,  the values are also very strange, whose max value is 976.

**Comment by lly2111101** [comment]
@dongzhuoyao Can you tell me why the class number is 19 in the code? Do you know how to get the "synthis_mapped_to_city" data when we use SYNTHIA dataset?

**Comment by WorkingCC** [comment]
@dongzhuoyao @chrisliu54 Could you tell me how to convert the labels from SYNTHIA which are of 3 channels to a normal labels like cityscapes and GTAV. I try to use  cv2.imread(your-image-path,cv2.IMREAD_UNCHANGED) but find what we get is still 3 channels.
