### ISSUE TITLE
the mIoU in Synthia dataset is only 28%

### ISSUE THREAD

**Issue by dongzhuoyao** [swamiviv/LSD-seg#4]
using default setting, the mIoU is 28%.

Does anybody else get better result?

I think the training of GAN is very tricky.

**Comment by swamiviv** [comment]
Let me get this right. For the complete synthia training, there are 19 classes. But following previous works and for fair comparison, we report results only on 16 classes. 3 classes (truck, train and terrain) are not reported. Please refer to our paper. Hence, your 28% actually amounts to ~33.5%. In our paper, we have reported the performance for 1024x512 sized images. For the size used commonly i.e. 640x320, our runs give 28.5-29.5%, which is close to what you are getting.

Hope this helps. Let me know.

**Comment by dongzhuoyao** [comment]
yes, you are right, thx!


==> Loading FCN8s_LSD model file: logs/MODEL-LSD_CFG-Adam_LR_0.00001000/model_best.pth.tar
==> Evaluating with CityScapes validation
tensorpack mIoU: 0.286795885361
tensorpack mean_accuracy: 0.385299141096
tensorpack accuracy: 0.798419604166
('Num classes', 19)
===>road:       78.47
===>sidewalk:   29.99
===>building:   75.9
===>wall:       6.9
===>fence:      0.85
===>pole:       21.73
===>light:      10.29
===>sign:       14.43
===>vegetation: 76.42
===>terrain:    0.0
===>sky:        77.73
===>person:     42.49
===>rider:      14.84
===>car:        62.78
===>truck:      0.0
===>bus:        11.48
===>train:      0.0
===>motocycle:  7.05
===>bicycle:    13.58
===> mIoU: 28.68

**class16-mIoU= 34.06**

**Comment by aserdega** [comment]
@dongzhuoyao. Hi, how did you manage to train it without mapped labels of SYNTHIA? Authors still have not provided this script :(

**Comment by xu7996** [comment]
> using default setting, the mIoU is 28%.
> 
> Does anybody else get better result?
> 
> I think the training of GAN is very tricky.


Hi, I also used the default setting, but the mIoU is very low.

===>road: 0.33
===>sidewalk: 0.0
===>building: 76.71
===>wall: 0.36
===>fence: 0.91
===>pole: 0.08
===>light: 0.3
===>sign: 1.24
===>vegetation: 0.23
===>terrain: 0.01
===>sky: 0.0
===>person: 0.36
===>rider: 0.51
===>car: 0.0
===>truck: 0.02
===>bus: 0.04
===>train: 0.0
===>motocycle: 3.06
===>bicycle: 0.0
===> mIoU: 4.43

I don't know what went wrong, are there any parameters that need to be adjusted?
Looking forward to your reply
